# Generated by Django 3.2.5 on 2021-07-30 23:25

from django.db import migrations, models
import kaos_storages.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='default')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', kaos_storages.fields.PrivateFileField(upload_to='private')),
            ],
        ),
        migrations.CreateModel(
            name='PublicFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', kaos_storages.fields.PublicFileField(upload_to='public')),
            ],
        ),
    ]
