name: dj-kaos-storages
version: 0.1.0-rc1
description: A set of django media storage classes for different use cases such as private file storage on S3

repo_url: https://github.com/kaoslabsinc/dj-kaos-storages
project_url: https://github.com/kaoslabsinc/dj-kaos-storages
keywords: django, storages, s3, boto, django-storages, kaos
